# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f72959499b198c24a77a61bd56b2b18a78ee876107f75f3f58fd409ceef41072da0ae072aa42384ad21d75ac771460b05d1687a88c09e4629c019059e9f8c9bb

test:
  secret_key_base: b7534e5ce92fb8105aa83f11d1043060fa215d8a4ca26e874eb33acf9a4f6ca117991a1152a120a7ff03e4d22592c1cb12e83da9cb20ab6370987abd44562ffa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
